### ISSUE TITLE
Testing: Resource Meta plugin

### ISSUE THREAD

**Issue by jimsafley** [omeka/plugin-ResourceMeta#1]
This plugin is almost identical to the [corresponding module](https://github.com/omeka-s-modules/ResourceMeta) for Omeka S. There are fewer convenience features, but it has the same core purpose and functionality. Test this by adding meta names to element set elements and see whether they appear as `<meta>` tags in the markup of item, file, and collection pages.

**Comment by allanaaa** [comment]
Was going to ask about meta count and automap, but you just said in the meeting they'll happen soonishly. So, testing done! Works great. Docs are ready for a lookover (I mostly copied the module text, so let me know if I missed an errant "resource template" mention somewhere).
